# Gunakan image Node.js sebagai dasar
FROM node:18

# Buat direktori kerja di dalam container
WORKDIR /frontend

# Salin package.json dan package-lock.json ke direktori kerja
COPY package*.json ./

# Install dependensi proyek
RUN npm install

# Salin seluruh file proyek ke direktori kerja
COPY . .

# Bangun aplikasi React untuk produksi
RUN npm run build

# Port yang digunakan oleh aplikasi
EXPOSE 3000

# Perintah untuk menjalankan aplikasi React
CMD [ "npm", "start" ]