version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4201:4201"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:3000"
    depends_on:
      - backend
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
