# Gunakan image Node.js sebagai dasar
FROM node:18

# Buat direktori kerja di dalam container
WORKDIR /backend

# Salin package.json dan package-lock.json ke direktori kerja
COPY package*.json ./

# Install dependensi proyek
RUN npm install

# Salin seluruh file proyek ke direktori kerja
COPY . .

# Port yang digunakan oleh aplikasi backend
EXPOSE 3001

# Perintah untuk menjalankan aplikasi Express
CMD [ "npm", "start" ]