//------------------------------------------------------------//

### CRUD Admin
POST http://194.233.93.124:4201/r
Content-Type: application/json

{
    "nama": "Admin",
    "username": "admin1234",
    "password": "admin321",
    "confPassword": "admin321",
    "role": "Admin"
}

### Login
POST http://194.233.93.124:4201/login
Content-Type: application/json

{
    "username": "daffa123",
    "password": "daffa321"
}

###
GET http://194.233.93.124:4201/personal/1

###
GET http://194.233.93.124:4201/personal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9ha3VuIjoyLCJ1c2VybmFtZV9ha3VuIjoiZGFmZmFyYWloYW5kaWthIiwicm9sZV9ha3VuIjoiVXNlciIsImlhdCI6MTY5NjMwOTUzNiwiZXhwIjoxNjk2MzA5NTUxfQ._Ao79uJgTfef25LcxCacEokIHsmgWsccITZ0JZRqJv4

### refresh token
GET http://194.233.93.124:4201/token

### logout
DELETE http://194.233.93.124:4201/logout

###
# GET http://194.233.93.124:4201/admin

###
# POST http://194.233.93.124:4201/admin/register
# Content-Type: application/json

# {
#     "username": "helsa",
#     "password": "helsa4213"
# }

###
# POST http://194.233.93.124:4201/admin/login
# Content-Type: application/json

# {
#     "username": "helsa",
#     "password": "helsa4213"
# }

//------------------------------------------------------------//

### CRUD DATA DIRI (Personal)
POST http://194.233.93.124:4201/personal
Content-Type: application/json
Authorization: Bearer <>

{
    "foto": "url", //kemungkinan besar bakal error jadi harus coba lewat postman
    "nama": "Muhammad Daffa Raihandika",
    "tempat_lahir" : "Bandung",
    "tanggal_lahir" : "2003-05-13",
    "usia" : 20,
    "tinggi_badan" : 160.0,
    "berat_badan" : 45.0,
    "alamat" : "Kota Cimahi, Jawa Barat, Indonesia",
    "agama" : "Islam",
    "jenis_kelamin" : "Laki-Laki",
    "telp" : "081572548494",
    "email" : "helsa.alika.tif421@polban.ac.id",
    "status" : "Mahasiswa",
    "instagram" : "daffabarudakbandungwell",
    "github" : "daaffaa",
    "linkedin" : "daffaraihandika",
    "id_akun": 2
}

### Find All
GET http://194.233.93.124:4201/personal
Authorization: Bearer 

### Find One
GET http://194.233.93.124:4201/personal/4
Authorization: Bearer <>

### Update
PATCH http://194.233.93.124:4201/personal/1
Content-Type: application/json
Authorization: Bearer <>
{
    "nama": "Helsa Alika"
}

### Delete
DELETE http://194.233.93.124:4201/personal/8
Authorization: Bearer <>

//------------------------------------------------------------//

### CRUD Portofolio
POST http://194.233.93.124:4201/portofolio
Content-Type: application/json

{
    "id_person": 1,
    "nama_portofolio": "CRUD expressJs",
    "deskripsi_portofolio": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem sed repudiandae saepe facilis id atque labore aspernatur. Doloribus voluptatibus sapiente alias voluptatem dolore, facere in consequuntur, delectus, esse nulla ipsam!",
    "file_portofolio": "url/portofolio/expressJs.pdf"
}

### Menampilkan semua portofolio berdasarkan id_person
GET http://194.233.93.124:4201/portofolio/2

### Menampilkan satu portofolio yang dipilih
GET http://194.233.93.124:4201/portofolio/1/2

### edit portofolio
PATCH http://194.233.93.124:4201/portofolio/2
Content-Type: application/json

{
    "nama_portofolio": "CRUD expressJs",
    "deskripsi_portofolio": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem sed repudiandae saepe facilis id atque labore aspernatur. Doloribus voluptatibus sapiente alias voluptatem dolore, facere in consequuntur, delectus, esse nulla ipsam!",
    "file_portofolio": "url/portofolio/expressJs.pdf"
}

###
DELETE http://194.233.93.124:4201/portofolio/1

//------------------------------------------------------------//

### CRUD Pendidikan
POST http://194.233.93.124:4201/pendidikan
Content-Type: application/json

{
    "id_person": 1,
    "instansi_pendidikan": "SMAN 2 Ngamprah",
    "jurusan": "IPS",
    "tahun_mulai_ajaran": "2017-09-01",
    "tahun_akhir_ajaran": "2020-06-30"
}

###
GET http://194.233.93.124:4201/pendidikan/1

###
GET http://194.233.93.124:4201/pendidikan/1/1

###
PATCH http://194.233.93.124:4201/pendidikan/1
Content-Type: application/json

{
    "id_person": 1,
    "instansi_pendidikan": "SMAN 2 Cijerah",
    "jurusan": "IPS",
    "tahun_mulai_ajaran": "2017-09-01",
    "tahun_akhir_ajaran": "2020-06-30"
}

###
DELETE http://194.233.93.124:4201/pendidikan/2

//------------------------------------------------------------//


# CRUD Organisasi

###Create an Organisasi 
POST http://194.233.93.124:4201/organisasi 
Content-Type: application/json

{
"id_person": 1, 
"nama_organisasi": "BEM Kema Polban", 
"posisi": "Ketua Departemen Kominfo", 
"tanggal_mulai_menjabat": "2022-01-25", 
"tanggal_akhir_menjabat": "2023-12-29"
}

### Get All Organisasi by id_person 
GET http://194.233.93.124:4201/organisasi/1

### Get a Specific Organisasi by id_person and id_organisasi 
GET http://194.233.93.124:4201/organisasi/1/1

### Update an Organisasi 
PATCH http://194.233.93.124:4201/organisasi/1 
Content-Type: application/json

{
"posisi": "Ketua Departemen Kominfo"
}

### Delete an Organisasi 
DELETE http://194.233.93.124:4201/organisasi/1

# CRUD Skill

### Create a Skill 
POST http://194.233.93.124:4201/skill 
Content-Type: application/json

{
    "id_person": 1, 
    "nama_skill": "Ruby", 
    "capability": "Expert dalam menggunakan bahasa Ruby"
}

### Get All Skill by id_person 
GET http://194.233.93.124:4201/skill/1

### Get a Specific Skill by id_person and id_skill 
GET http://194.233.93.124:4201/skill/1/1

### Update a Skill 
PATCH http://194.233.93.124:4201/skill/1 
Content-Type: application/json

{
"capability": "Expert dalam menggunakan bahasa Ruby dan Python"
}

###
DELETE http://194.233.93.124:4201/skill/1